export const CREATE_FIRST_FIELD = 'CREATE_FIRST_FIELD';
export const CREATE_SECOND_FIELD = 'CREATE_SECOND_FIELD';
export const SHOW_RESULT = 'SHOW_RESULT';
export const RANDOM_SELECTION_NUMBERS = 'RANDOM_SELECTION_NUMBERS';